# Base config
width: 800
height: 300
background: '#FFFFFF'  # optional
filename: drinkup.png  # optional

# Default fonts
fonts:
  regular: assets/fonts/LeagueGothicCyrillic.ttf
  special: assets/fonts/Raleway-Bold.ttf

# Elements
elements:
  - type: rectangle
    position: [0, 0]
    size: [800, 300]
    color: '#00b8b8'

  - type: text
    text: >
      дринкапъ
    position: [201, 53]
    font: regular
    font_size: 152
    color: '#000000'

  - type: text
    text: >
      дринкапъ
    position: [204, 50]
    font: regular
    font_size: 150
    color: '#f3f3eb'
