# Base config
width: 800
height: 300
background: '#FFFFFF'  # optional
filename: berlin.png  # optional

# Default fonts
fonts:
  regular: assets/fonts/LeagueGothicCyrillic.ttf
  special: assets/fonts/Raleway-Bold.ttf

# Elements
elements:
  - type: rectangle
    position: [0, 0]
    size: [800, 300]
    color: '#3dbd5d'

  - type: text
    text: |
      Python Users
      Berlin
    position: [20, 20]
    font: special
    font_size: 45
    color: '#303030'

  - type: text
    text: >
      The future of pythonic web: ASGI & Daphne
    position: [20, 140]
    font: regular
    font_size: 45
    color: '#FFF9FF'

  - type: text
    text: Dmitry Nazarov, EXANTE
    position: [20, 220]
    font: regular
    font_size: 30
    color: '#fbfbfb'

  - type: image
    src: https://docs.poppy-project.org/en/img/logo/python.png
    position: [317, 22]
    size: [244, 104]

  - type: ellipse
    position: [595, 10]
    size: [190, 190]
    color: '#fbfbfb'

  - type: round_image
    src: https://pbs.twimg.com/profile_images/856843437273993216/lsl10k5x_400x400.jpg
    position: [600, 15]
    size: [182, 182]
    crop: [0, 0, 180, 180]
